### ISSUE TITLE
Update EZGui classes to work seamlessly with layouts

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1685]
Currently, attempting to add any EZGui view into a Qt layout will produce a warning *Qt: WARNING: Do not know how to use an instance of class 'EZKnob'* and incorrect behavior.

https://github.com/supercollider/supercollider/tree/topic/EZGuiForLayouts is a substantial reworking of the main EZGui classes for full compatibility with layouts. The work is not completely done, however:

- In EZSlider, for instance, with the normal horizontal layout, the slider occupies the entire vertical space allotted by the parent view, but the number box's height adapts to the font. It would look cleaner if all subviews had the same height, but this is not possible with the current size-hinting interface.

- I couldn't find any clear spec for the layout symbols, e.g. `\horz`, `\vert`, `\line2`. I tested `\horz` and `\vert` briefly and the four classes behave reasonably in those two cases. I am not an extensive/detailed user of EZGuis, so it would help if somebody who knows these layout options better could handle them or provide advice.

- This will break user subclasses, by removing `prSubViewBounds` (not needed because the subviews' bounds are now under control of the layout) and `prSetViewParams` (because subviews' resize behavior is also under control of the layout). So I would say, don't put this in 3.7.

Other developers are welcomed/encouraged/begged to improve on this :)

Test cases:

```
// EZSlider \horz
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = VLayout(
	*(e = { EZSlider(w, nil, "test", nil, nil, 0.5) } ! 5)
);

// EZSlider \vert
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = HLayout(
	*(e = { EZSlider(w, nil, "test", nil, nil, 0.5, layout: \vert) } ! 5)
);

// EZKnob \horz -- hmm, this is perhaps dubious
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = VLayout(
	*(e = { EZKnob(w, nil, "test", nil, nil, 0.5) } ! 5)
);

// EZKnob \vert
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = HLayout(
	*(e = { EZKnob(w, nil, "test", nil, nil, 0.5) } ! 5)
);

w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = VLayout(
	*(e = { EZNumber(w, nil, "test", nil, nil, 0.5) } ! 5)
);

// EZRanger \horz
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = VLayout(
	*(e = { EZRanger(w, nil, "test", nil, nil, [0.3, 0.7]) } ! 5)
);

// EZRanger \vert
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = HLayout(
	*(e = { EZRanger(w, nil, "test", nil, nil, [0.3, 0.7], layout: \vert) } ! 5)
);
```

**Comment by shimpe** [comment]
it would be nice if this issue could get some attention!

thanks

**Comment by retroriff** [comment]
Same problem here. EZ wrapper classes can't be attached to layouts: 

> ERROR: Message 'asView' not understood.

**Comment by jamshark70** [comment]
Bit disappointed to note that my questions went 3.5 years without any attention. OK.

Well, if I have time, I'll try to fix this up and make it a pull request.

**Comment by geoffroymontel** [comment]
I've just run into this problem :)

**Comment by jamshark70** [comment]
Make that 4.5 years now.

Requoting the questions:

- In EZSlider, for instance, with the normal horizontal layout, the slider occupies the entire vertical space allotted by the parent view, but the number box's height adapts to the font. It would look cleaner if all subviews had the same height, but this is not possible with the current size-hinting interface.
- I couldn't find any clear spec for the layout symbols, e.g. \horz, \vert, \line2. I tested \horz and \vert briefly and the four classes behave reasonably in those two cases. I am not an extensive/detailed user of EZGuis, so it would help if somebody who knows these layout options better could handle them or provide advice.
- This will break user subclasses, by removing prSubViewBounds (not needed because the subviews' bounds are now under control of the layout) and prSetViewParams (because subviews' resize behavior is also under control of the layout.

See https://github.com/supercollider/supercollider/tree/topic/EZGuiForLayouts.

**Comment by shimpe** [comment]
If it will break user code, perhaps another option is to make a new version of EzGui classes (with a different name), and deprecate the old ones?The new ones then have no legacy behavior to worry about.

**Comment by jamshark70** [comment]
> If it will break user code, perhaps another option is to make a new version of EzGui classes (with a different name), and deprecate the old ones?

Sure, I'd be ok with that. (I eventually added LayoutValueSlider in one of my Quarks for exactly this reason.)

The weakness in size hinting is extremely annoying though. We might just have to live with it, as almost half a decade later, there's no concrete idea how to improve it.

The problem is: Currently you can specify either a fixed size (in either dimension) or a maximum, but the interface has no way to express the idea of a view that always conforms to the parent view's size (i.e., if the view is a member of an HLayout, its height may reasonably fill the entire HLayout's height, or width in a VLayout). Slider behaves this way by default, but NumberBox does not, and I could never find any way to make it do so. So an EZSlider in an HLayout with a relatively large height will look stupid (the number box will be considerably less tall than the slider).

To make it not look stupid, size hinting needs a new feature.

**Comment by jamshark70** [comment]
Here's what I mean by "looks stupid."

```supercollider
(
w = Window("test", Rect(800, 200, 500, 400));
w.layout = VLayout(
	*Array.fill(4, {
		HLayout(
			NumberBox().fixedWidth_(100),
			Slider().orientation_(\horizontal)
		)
	})
);
w.front;
)
```

![ezslider-layout](https://user-images.githubusercontent.com/318301/77139739-22df3d80-6ab2-11ea-8f8f-18c6193a1ab1.png)

I'd like to be able to say `NumberBox().fixedWidth_(100).fillHeight` or something, but this doesn't exist. (We have `minHeight_`, `maxHeight_` and `fixedHeight_` but none of these does what is needed.)

**Comment by shimpe** [comment]
Some more funny behaviour:

// the following looks less stupid but it does something I didn't expect
// and probably not what you wanted
(
w = Window("test", Rect(800, 200, 500, 400));
w.layout = VLayout(
	*Array.fill(4, {
		HLayout(
			VLayout([NumberBox().fixedWidth_(100), stretch:1]),
			Slider().orientation_(\horizontal)
		)
	})
);
w.front;
)

![Screenshot_20200320_083506](https://user-images.githubusercontent.com/732258/77144082-db8a8a00-6a7c-11ea-8c81-c5f1955cde0a.png)

**Comment by jamshark70** [comment]
> Some more funny behaviour:

That's an improvement, though the empty space looks awkward.

Tbh, it may not be an improvement to have a 50-px tall number box with 12 pixel text in it.

**Comment by eleses** [comment]
Just a note here that EZSlider has "special juju" when you double click its label: it turns into Spec edit mode. In general, if you "steal" its components into some other view than that it was created with, that spec-edit-mode stops working. If you want 100% backwards compat, you'd have to make that work too.

**Comment by jamshark70** [comment]
> when you double click its label: it turns into Spec edit mode. In general, if you "steal" its components into some other view than that it was created with, that spec-edit-mode stops working...

I'd not recommend stealing views into layouts. (I realize you arrived at that approach on the forum for some uses, and that's fine for an individual hack, but I wouldn't do it in the main class library.) It would be better to build the views in a sensible Layout and completely bypass FlowLayout if a Qt layout is being used.

It would be tricky to get both to work in the same class, so Nathan might be right that it would be better to have alternate classes for layout support.

Once you do that, then StackLayout is perfect for switching modes.

**Comment by prko** [comment]
@capital-G 
Could this be resolved in version 3.15?

**Comment by capital-G** [comment]
If someone comes up with a PR, sure :)

**Comment by jamshark70** [comment]
> If someone comes up with a PR, sure :)

https://github.com/supercollider/supercollider/tree/topic/EZGuiForLayouts still exists as a starting point (though it needs to be rebased to incorporate the 8000+ commits since then lol).
