### ISSUE TITLE
SCDoc code examples appear with non-monospace font

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#4091]
OSX 10.13.6
SC 3.9.3

Maybe partially related to  #3863 and #3876
It sometimes occured under earlier OSX version, but it seems to be always the case now, I get code in Times. As the help fonts cannot be enlarged (with the exception of the case of a missing document docklet) this makes reading and changing help files quite uncomfortable.

**Comment by dkmayer** [comment]
`reading and changing help files `

Sorry, meant: reading and changing help file code

**Comment by gusano** [comment]
@dkmayer I tried on OSX 10.13.6 and on linux and I cannot reproduce that.
Do you have a custom.css somewhere?
Could you try opening an help file from a browser and check it there? (dev console might help to see where the issue could comes from)

**Comment by dkmayer** [comment]
> Do you have a custom.css somewhere?

None that I'm aware of. Indeed the representation is ok if I open the html file in a browser. 
I rechecked installing SC from scratch, no extensions, no quarks. Here's the system log

```
Sep 30 21:46:54 Daniels-MacBook-Pro scsynth[626]: BUG in libdispatch client: dispatch_mig_server: mach_msg() failed (ipc/send) msg too small - 0x10000008
Sep 30 21:46:54 Daniels-MacBook-Pro systemstats[50]: assertion failed: 17G2208: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Sep 30 21:46:58 Daniels-MacBook-Pro Finder[283]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
Sep 30 21:46:59 Daniels-MacBook-Pro kcm[641]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?
Sep 30 21:48:07 Daniels-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit

```

**Comment by snappizz** [comment]
i am 99% sure this is fixed in 3.10. please try the 3.10 or develop branch.

**Comment by htor** [comment]
this is still an issue here on my mac, in latest build 3.10.2, 834c036d.
after fresh install, when opening sc, the help browser uses serif-font:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/1709263/52561962-3921c100-2dfd-11e9-9c11-05724392980e.png">

when looking in preferences, the font is set to `Monaco`. selecting it again from the list and hitting OK  applies the correct font and the issue is gone permanently.

**Comment by brianlheim** [comment]
Stale/cannot repro

**Comment by htor** [comment]
please re-open. 
i can reproduce this behaviour:

1. remove ~/Library/Application Support/SuperCollider:
`rm -rf ~/Library/Application Support/SuperCollider`
2. open supercollider and find a code example in the help browser
3. it is displayed in serif-font
4. open settings with cmd+, and hit the 'Save' button
5. it will display in monospace

reason is:
after step 1:
```
~/Library/Application Support $ cat SuperCollider/sc_ide_conf.yaml 
IDE:
  postWindow:
    lineWrap: false
~/Library/Application Support $ 
```

after step: 4
```
~/Library/Application Support $ cat SuperCollider/sc_ide_conf.yaml 
IDE:
  postWindow:
    lineWrap: false~/Library/Application Support $ cat SuperCollider/sc_ide_conf.yaml 
IDE:
  editor:
    blinkDuration: 600
    disableBlinkingCursor: false
    font:
      antialias: 2
      family: Monaco
      size: 13
    highlightBracketContents: true
    highlightCurrentLine: false
    inactiveEditorFadeAlpha: 64
    indentWidth: 4
    insertMatchingTokens: false
    lineWrap: true
    spaceIndent: false
    stepForwardEvaluation: false
    theme: default
    useComboBox: false
    useComboBoxWhenSplitting: false
  interpreter:
    autoStart: true
    configFile: ""
    runtimeDir: ""
    standalone: false
  postWindow:
    lineWrap: false
    scrollback: 1000
  startWithSession: last
~/Library/Application Support $ 
```

**Comment by brianlheim** [comment]
so it only happens when you delete the configuration folder? this doesn't seem important enough to try to fix. if it occurs under normal usage then we have a problem.

**Comment by htor** [comment]
@brianlheim no, it basically happens the first time users install supercollider. so i would argue this is normal usage

**Comment by lars-erik** [comment]
I installed 3.11 on Windows 10 today. The help browser displayed code with a serif font (times new roman). I opened the preferences and clicked apply, and the font immediately changed to monospace. Without having looked at any source, I'd imagine this is just a lack of default config?
